[metadata]
description  = "A channel to select files and directories"
name         = "files"
requirements = ["bat", "fd"]

[source]
command = "fd -t f"

[preview]
command = "bat -n --color=always '{}'"
env     = { BAT_THEME = "Catppuccin Mocha" }

[ui]
preview_panel = { "size" = 70, "scrollbar" = true }

[keybindings]
shortcut = "f1"
